# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec4af1eedaba3ccd3b3dc3afdc0a79e12f1beee3567fe6b0dbfe61d40951793d5b0779c9a770d74fe89a5798eb1cca0dd9db562a87a4077658221e62734cc5a

test:
  secret_key_base: 74ab66b4703bca8920003516ef092f32c13c6ad24eef79b204700190992e83f17da74751fd3b8ea61200004ed647987ad9ef0dc60414ad904f62565e7872e143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
